// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"
	request "gotu/bookstore/internal/request"

	mock "github.com/stretchr/testify/mock"

	types "gotu/bookstore/internal/types"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) CreateOrder(ctx context.Context, req *request.OrderRequest) (*types.Order, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *types.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.OrderRequest) (*types.Order, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.OrderRequest) *types.Order); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.OrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOrdersByUserId provides a mock function with given fields: ctx, userID
func (_m *OrderService) ListOrdersByUserId(ctx context.Context, userID int64) ([]*types.OrderView, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListOrdersByUserId")
	}

	var r0 []*types.OrderView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*types.OrderView, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*types.OrderView); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.OrderView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
